### ISSUE TITLE
Matrix-math example - ImportError...

### ISSUE THREAD

**Issue by Bandsberg** [bytecodealliance/componentize-py#50] opened 2023-12-29 16:12 UTC
Following the example of matrix-math [fd5b49c](https://github.com/bytecodealliance/componentize-py/commit/fd5b49cd1e7303dab8a4c93c0432aa07f790b04e) I get the following error when running `componentize-py -d ../../wit -w matrix-math componentize app -o matrix-math.wasm`:
```

warning: site-packages directory not found under /home/jes/gitrepositories/wasmcloud_test/my-py-component-wasmtime16-0-0/myenv/lib
Traceback (most recent call last):
  File "/home/jes/.local/bin/componentize-py", line 8, in <module>
    sys.exit(script())
             ^^^^^^^^
AssertionError: Traceback (most recent call last):
  File "/0/app.py", line 5, in <module>
    import numpy
  File "/0/numpy/__init__.py", line 157, in <module>
    from . import random
  File "/0/numpy/random/__init__.py", line 180, in <module>
    from . import _pickle
  File "/0/numpy/random/_pickle.py", line 1, in <module>
    from .mtrand import RandomState
ImportError: dynamic module does not define module export function (PyInit_mtrand)


Caused by:
    ImportError: dynamic module does not define module export function (PyInit_mtrand)
```

I am using python 3.12 and have created an enviroment using virtualenv
I am more experienced in Rust than python and have been unable to figure out if it is an error on my side or with the example.

**Comment by dicej** [comment] 2024-01-03 15:27
Thanks for reporting this!  I wasn't able to reproduce this on MacOS with Python 3.12, but I did get something similar on Linux.  I'll start digging into it.

**Comment by dicej** [comment] 2024-01-03 16:21
The issue I hit on Linux seems to be due to the issue addressed by https://github.com/bytecodealliance/wasm-tools/pull/1341.  Updating to the main branch of `wasm-tools` fixed it.  I'll open a PR shortly to update the `wasm-tools` dep and then publish a 0.9.1 release once CI is finished.

In my case, the function it was complaining about was `PyInit__multiarray_umath` rather than `PyInit_mtrand`, but I suspect the underlying cause was the same.

**Closed** 2024-01-03 16:57 UTC

**Comment by dicej** [comment] 2024-01-03 17:42
@Bandsberg when you have a chance, please try again with `componentize-py` 0.9.1 and let me know if you still have trouble.
