### ISSUE TITLE
ImportError with NumPy when running matrix_math example

### ISSUE THREAD

**Issue by erlingto** [bytecodealliance/componentize-py#92] opened 2024-06-12 21:33 UTC
Hi,
I'm trying to run the matrix_math example, but I'm encountering the following error when executing the componentize-py command::

"ImportError:
    IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

    Importing the numpy C-extensions failed. This error can happen for
    many reasons, often due to issues with your setup or how NumPy was
    installed.

    We have compiled some common reasons and troubleshooting tips at:

        https://numpy.org/devdocs/user/troubleshooting-importerror.html

    Please note and check the following:

      * The Python version is: Python3.12 from ""
      * The NumPy version is: "1.26.0b1"

    and make sure that they are the versions you expect.
    Please carefully study the documentation linked above for further help.

    Original error was: library not found
"
I'm sure that this issue is not directly related to componentize.py because I encounter the same error when running the Python script using python app.py.

Has anyone else come across this issue and found a solution? I've been troubleshooting for a while without success. From what I can tell, the NumPy version should be compatible with the Python version I'm using.

Any help would be greatly appreciated :)

**Comment by dicej** [comment] 2024-06-12 21:45
Assuming you've followed the directions in https://github.com/bytecodealliance/componentize-py/blob/main/examples/matrix-math/README.md, it actually makes sense you'd get that error when running `python app.py` directly, because `numpy-wasi.tar.gz` only has .so files built for WASI, and your native `python` won't be able to load them.

I just tried following the directions in that README.md and it worked for me.  What platform are you using?  Does it help to use a virtual environment (e.g. `python3 -m venv .venv && source .venv/bin/activate` before running the other instructions)?

**Comment by erlingto** [comment] 2024-06-12 23:27
Ohh, does this mean I will only be able to use "modified" packages with this? 

I just reinstalled Python and attempted the example again.

These are the steps im doing (From the "\examples\matrix-math" directory):  
- cargo install --version 18.0.0 wasmtime-cli
- pip install componentize-py==0.13.3
- curl -o numpy-wasi.tar.gz https://github.com/dicej/wasi-wheels/releases/download/v0.0.1/numpy-wasi.tar.gz  (my terminal wont accept -OL for some reason, but these two steps should just be downloading and unpacking the file right?) 
- tar xf numpy-wasi.tar.gz

Then when im running:
 "componentize-py -d ../../wit -w matrix-math componentize app -o matrix-math.wasm" 
 
 I get the same error as before, im on a windows computer at the moment running the commands from Command Prompt . Might try to test the example on a different computer tomorrow.

**Comment by dicej** [comment] 2024-06-12 23:48
> Ohh, does this mean I will only be able to use "modified" packages with this?

Pure Python packages should work straight from e.g. pypi.org.  Packages which contain native extensions (such as NumPy) must be built for WASI (i.e. the Mac, Windows, and Linux builds won't work).  Some day, package maintainers will be able to publish WASI builds to pypi.org alongside the existing Mac, Windows, and Linux builds, but we're not there yet.  Hence the `wasi-wheels` repo linked to in the instructions.

> These are the steps im doing (From the "\examples\matrix-math" directory):
> 
>     * cargo install --version 18.0.0 wasmtime-cli
> 
>     * pip install componentize-py==0.13.3
> 
>     * curl -o numpy-wasi.tar.gz https://github.com/dicej/wasi-wheels/releases/download/v0.0.1/numpy-wasi.tar.gz  (my terminal wont accept -OL for some reason, but these two steps should just be downloading and unpacking the file right?)
> 
>     * tar xf numpy-wasi.tar.gz
> 
> Then when im running: "componentize-py -d ../../wit -w matrix-math componentize app -o matrix-math.wasm"

That all looks reasonable to me.  I don't have a Windows machine handy at the moment, but I'll give it a try when I have a chance.

**Comment by dicej** [comment] 2024-06-13 20:52
Okay, I managed to reproduce this on Windows; I'll dig into it.

**Comment by dicej** [comment] 2024-06-13 22:02
Ugh, looks like a back-slash-vs-forward-slash issue in the paths `wit-component` is generating to populate the `dlopen` table.  I guess this has probably never worked right on Windows :facepalm:

Thanks for reporting this.  I'll start working on a fix.

**Comment by dicej** [comment] 2024-06-14 15:53
This should be fixed in #93.  I'll be releasing v0.13.4 once that's merged and CI finishes.

**Comment by dicej** [comment] 2024-06-14 18:50
I've released v0.13.4 with the fix; please let me know if you still have any issues.

**Closed by dicej** 2024-06-14 18:50 UTC

**Comment by erlingto** [comment] 2024-06-14 18:53
Great, Thanks! I will test it tommorow :)
